Raise minimum rustc version to 1.48
Required by use of std::future::ready in tokio:

    error[E0658]: use of unstable library feature 'future_readiness_fns'
      --> github.com-1ecc6299db9ec823/tokio-1.17.0/src/net/addr.rs:21:23
       |
    21 | type ReadyFuture<T> = future::Ready<io::Result<T>>;
       |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'future_readiness_fns'
      --> github.com-1ecc6299db9ec823/tokio-1.17.0/src/net/addr.rs:58:9
       |
    58 |         future::ready(Ok(iter))
       |         ^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'future_readiness_fns'
      --> github.com-1ecc6299db9ec823/tokio-1.17.0/src/net/addr.rs:98:9
       |
    98 |         future::ready(Ok(iter))
       |         ^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'future_readiness_fns'
       --> github.com-1ecc6299db9ec823/tokio-1.17.0/src/net/addr.rs:140:9
        |
    140 |         future::ready(Ok(iter))
        |         ^^^^^^^^^^^^^