Raise minimum required compiler to rustc 1.42
Required by way of our dependency on reqwest -> hyper -> h2 ->
tracing -> tracing-core.

    error[E0658]: use of unstable library feature 'matches_macro'
       --> .cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.18/src/event.rs:104:9
        |
    104 |         matches!(self.parent, Parent::Root)
        |         ^^^^^^^