Raise minimum rustc version to 1.49
Required by use of std::hint::spin_loop in tokio:

    error[E0658]: use of unstable library feature 'renamed_spin_loop'
      --> github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/mod.rs:29:20
       |
    29 |     pub(crate) use std::hint::spin_loop;
       |                    ^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'renamed_spin_loop'
       --> github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/mod.rs:100:9
        |
    100 |         std::hint::spin_loop();
        |         ^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'renamed_spin_loop'
       --> github.com-1ecc6299db9ec823/tokio-1.17.0/src/sync/task/atomic_waker.rs:285:17
        |
    285 |                 hint::spin_loop();
        |                 ^^^^^^^^^^^^^^^