Raise minimum tested compiler to 1.71
Required by `opener`. On older versions:

    error: failed to select a version for `opener`.
        ... required by package `star-history v1.0.20`
    versions that meet the requirements `^0.7` (locked to 0.7.0) are: 0.7.0

    the package `star-history` depends on `opener`, with features: `dbus` but `opener` does not have these features.
     It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

    failed to select a version for `opener` which could resolve this conflict