Bump oldest rustc tested to 1.56.1
Required by 2021 edition in hashbrown.

    error: failed to parse manifest at github.com-1ecc6299db9ec823/hashbrown-0.12.1/Cargo.toml

    Caused by:
      failed to parse the `edition` key

    Caused by:
      this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.