Raise minimum rust version to 1.47
Required by use of Result::as_deref in the pkg-config crate.

    error[E0658]: use of unstable library feature 'inner_deref'
       --> pkg-config-0.3.21/src/lib.rs:163:53
        |
    163 |                         let crate_name = crate_name.as_deref().unwrap_or("sys");
        |                                                     ^^^^^^^^