Raise required compiler to rust 1.73
Required by the most recent release of bstr.

    error: package `bstr v1.11.0` cannot be built because it requires rustc 1.73 or newer, while the currently active rustc version is 1.71.1
    Either upgrade to rustc 1.73 or newer, or use
    cargo update -p bstr@1.11.0 --precise ver
    where `ver` is the latest version of `bstr` supporting rustc 1.71.1