Raise minimum tested compiler to 1.70
Required by transitive dependency on the `home` crate:

    error: package `home v0.5.9` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.65.0
    Either upgrade to rustc 1.70.0 or newer, or use
    cargo update -p home@0.5.9 --precise ver
    where `ver` is the latest version of `home` supporting rustc 1.65.0